// ============================================================================
// AUTO-GENERATED BY MIDNIGHT COMPACT COMPILER (language_version: 0.15.0)
// Contract: allowlist.compact
// Target: TypeScript Declarations & Managed Bindings
// ============================================================================

import type * as __compactRuntime from '@midnight-ntwrk/compact-runtime';

export type Witnesses<PS> = {
  secretKey(context: __compactRuntime.WitnessContext<Ledger, PS>): [PS, Uint8Array] | Promise<[PS, Uint8Array]>;
  merklePath(context: __compactRuntime.WitnessContext<Ledger, PS>): [PS, [Uint8Array, Uint8Array, Uint8Array, Uint8Array, Uint8Array]] | Promise<[PS, [Uint8Array, Uint8Array, Uint8Array, Uint8Array, Uint8Array]]>;
  pathDirections(context: __compactRuntime.WitnessContext<Ledger, PS>): [PS, [boolean, boolean, boolean, boolean, boolean]] | Promise<[PS, [boolean, boolean, boolean, boolean, boolean]]>;
};

export type ImpureCircuits<PS> = {
  publishAllowlist(context: __compactRuntime.CircuitContext<PS>, newRoot_0: Uint8Array): __compactRuntime.CircuitResults<PS, []>;
  checkAccess(context: __compactRuntime.CircuitContext<PS>): __compactRuntime.CircuitResults<PS, []>;
};

export type PureCircuits = {
  publicStats(context: __compactRuntime.QueryContext<Ledger>): [Uint8Array, bigint];
};

export type Circuits<PS> = {
  publishAllowlist(context: __compactRuntime.CircuitContext<PS>, newRoot_0: Uint8Array): __compactRuntime.CircuitResults<PS, []>;
  checkAccess(context: __compactRuntime.CircuitContext<PS>): __compactRuntime.CircuitResults<PS, []>;
  publicStats(context: __compactRuntime.QueryContext<Ledger>): [Uint8Array, bigint];
};

export type Ledger = {
  readonly allowlistRoot: Uint8Array;
  readonly issuer: Uint8Array;
  readonly accessGranted: bigint;
  readonly nullifiers: Set<string>;
};

export declare class Contract<PS, W extends Witnesses<PS> = Witnesses<PS>> implements __compactRuntime.Contract<PS, W> {
  readonly circuits: Circuits<PS>;
  readonly witnesses: W;
  readonly initialPrivateState?: PS;
  constructor(witnesses: W, initialPrivateState?: PS);
  initialState(context: __compactRuntime.ConstructorContext<PS>, initialRoot: Uint8Array): __compactRuntime.ConstructorResult<PS>;
}

export declare function ledger(state: __compactRuntime.StateValue): Ledger;

export declare const contractReference: __compactRuntime.ContractReference;
