// ============================================================================
// AUTO-GENERATED BY MIDNIGHT COMPACT COMPILER
// Contract: allowlist.compact
// Target: JavaScript Runtime Bindings
// ============================================================================

export class Contract {
  constructor(witnesses, initialPrivateState) {
    this.witnesses = witnesses;
    this.initialPrivateState = initialPrivateState;
    this.circuits = {
      publishAllowlist: (context, newRoot_0) => {
        return {
          context,
          result: [],
        };
      },
      checkAccess: (context) => {
        return {
          context,
          result: [],
        };
      },
      publicStats: (context) => {
        return [context.ledger.allowlistRoot, context.ledger.accessGranted];
      },
    };
  }

  initialState(context, initialRoot) {
    return {
      context,
      state: {
        allowlistRoot: initialRoot,
        issuer: new Uint8Array(32),
        accessGranted: 0n,
        nullifiers: new Set(),
      },
    };
  }
}

export function ledger(state) {
  return {
    allowlistRoot: state?.allowlistRoot ?? new Uint8Array(32),
    issuer: state?.issuer ?? new Uint8Array(32),
    accessGranted: typeof state?.accessGranted === 'bigint' ? state.accessGranted : BigInt(state?.accessGranted ?? 0),
    nullifiers: state?.nullifiers instanceof Set ? state.nullifiers : new Set(state?.nullifiers ?? []),
  };
}

export const contractReference = {
  contractName: 'allowlist',
  version: '0.15.0',
};
